### ISSUE TITLE
CI'da Ruby inşaları sadece master dalında gerçekleşsin

### ISSUE THREAD

**Issue by roktas** [omu/rubian#1]
Geliştirme topic dallarında yapılıyor.  Her inşada [Ruby inşalarının](https://github.com/alaturka/rubian/blob/master/.circleci/config.yml#L21) tetiklenmesi gerekmiyor.  İnşalar da dahil tam testler master veya dev dalında yapılsın, diğer dallarda yapılmasın.

**Comment by huseyin** [comment]
@roktas Hocam iş kaydı başlığını değiştirdim. Bence dalları şöyle kullanalım:

- Öntanımlı dal `dev` olsun
- Geliştirmeleri "topic branch"lerde yapalım ve `dev` dalına alalım
- `dev` dalına aldığımız değişikliklerde "rubian" testlerini yapalım
- Sadece `master` dalına alınan değişikliklerde inşa öncesi testler (varsa) ve Ruby inşaları yapalım
