### ISSUE TITLE
Name change 

### ISSUE THREAD

**Issue by CufeHaco** [omu/rubian#12]
Please change the name.  My project name is Rubian, which I've started 4 years ago.  It's a cli shell for debian linux.

**Comment by CufeHaco** [comment]
![Screenshot_20200913-174524_Chrome](https://user-images.githubusercontent.com/16202445/93029512-5c1fe280-f5e9-11ea-826c-25dd0eed760b.jpg)

**Comment by roktas** [comment]
With all my due respect, no.
